on:
  workflow_dispatch:
    inputs:
      pull-request-number:
        type: number
        description: The number of your PR
        required: true
  pull_request:
    types:
      - closed

permissions:
  contents: none

jobs:
  clean:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        variant:
          - buildah-cached
          - buildah-cached/layer-cache
          - cached
          - cached/layer-cache
          - dual
          - dual/layer-cache
          - dual-buildah/layer-cache
          - dual-buildah
          - for-cleaning
          - merged
    env:
      PR_NUMBER: ${{ inputs.pull-request-number || github.event.pull_request.number }}
    steps:
      - id: encode-name
        run: |
          PACKAGE_NAME="pull-request-${PR_NUMBER}/${{ matrix.variant }}"
          # Poor man's urlencode
          ENCODED="${PACKAGE_NAME//\//%2F}"
          echo "package-name=${ENCODED}" >> "$GITHUB_OUTPUT"
      - run: >
          gh api
          --method DELETE 
          -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          /orgs/${{ github.repository_owner}}/packages/container/${{ steps.encode-name.outputs.package-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_PACKAGE_CLEANUP_TOKEN }}
