on:
  workflow_call:
    inputs:
      additional-build-args:
        type: string
        required: false
      containerfile:
        type: string
        required: false
      context:
        type: string
        required: false
      digest-artifact-name:
        type: string
        required: false
      image-name:
        type: string
        required: false
      platform:
        type: string
        required: false
        default: linux/amd64
      push-image:
        type: boolean
        required: true
      summarize-build:
        type: boolean
        required: false
        default: false
      target:
        type: string
        required: false
      version:
        type: string
        required: false
      tag-suffix:
        type: string
        required: false
      timeout-minutes:
        type: number
        required: false
        default: 360
    outputs:
      digest:
        value: ${{ jobs.build.outputs.digest }}
      image-name:
        value: ${{ jobs.build.outputs.image-name }}
      image-tag:
        value: ${{ jobs.build.outputs.image-tag }}
      image-name-with-tag:
        value: "${{ jobs.build.outputs.image-name }}:${{ jobs.build.outputs.image-tag }}"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout-minutes }}
    outputs:
      digest: ${{ steps.build.outputs.digest }}
      image-name: ${{ steps.ids.outputs.image-name }}
      image-tag: ${{ steps.ids.outputs.image-tag }}
    steps:
      - name: Set up QEMU
        if: inputs.platform != 'linux/amd64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ inputs.platform }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.platform }}
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Log in to GitHub Container Registry
        if: inputs.push-image
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: actions/checkout@v4
        if: inputs.context && !contains(inputs.context, '{{defaultContext}}')
      - name: Set image name and tag outputs
        id: ids
        run: |
          echo "image-name=ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ inputs.image-name || env.GITHUB_REPOSITORY_NAME_PART_SLUG }}" >> "$GITHUB_OUTPUT"
          echo "image-tag=${{ inputs.version || github.sha }}${{ inputs.tag-suffix }}" >> "$GITHUB_OUTPUT"
      - name: Build container image
        id: build
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_NO_SUMMARY: ${{ !inputs.summarize-build }}
        with:
          push: ${{ inputs.push-image }}
          build-args: |
            APP_VERSION=${{ inputs.version || github.sha }}
            ${{ inputs.additional-build-args }}
          context: ${{ inputs.context }}
          file: ${{ inputs.containerfile }}
          platforms: ${{ inputs.platform }}
          provenance: false
          tags: "${{ steps.ids.outputs.image-name }}:${{ steps.ids.outputs.image-tag }}"
          target: ${{ inputs.target }}
      - name: Write digest to artifact
        if: inputs.push-image && inputs.digest-artifact-name
        run: |
          digest="${{ steps.build.outputs.digest }}"
          mkdir digests
          touch "digests/${digest#sha256:}"
      - name: Upload digest
        if: inputs.push-image && inputs.digest-artifact-name
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.digest-artifact-name }}
          path: digests/*
          if-no-files-found: error
          retention-days: 1
