on:
  workflow_call:
    inputs:
      variant-digests:
        type: string
        required: true
        description: > 
          Newline-separated list of image digests. 
          If this is only one line, it's interpreted as an artifact name to download.
      image-name:
        type: string
        required: false
      tag:
        type: string
        required: false

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Download digest artifacts
        uses: actions/download-artifact@v3
        if: "!contains(inputs.variant-digests, '\n')"
        with:
          name: ${{ inputs.variant-digests }}
          path: /tmp/digests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Create manifest list and push
        run: |
          name="ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ inputs.image-name || env.GITHUB_REPOSITORY_NAME_PART_SLUG }}"
          
          digests=""
          if [ -d /tmp/digests ]
          then
            cd /tmp/digests
            digests=$(printf "${name}@sha256:%s " *)
          else
            digests=$(echo -n "${{ inputs.variant-digests }}" | while read -r digest; do printf '%s@%s ' "$name" "$digest"; done)
          fi
          
          tag="${name}:${{ inputs.tag || github.sha }}"
          docker buildx imagetools create -t "$tag" $digests
