on:
  pull_request:
    types:
      - closed

jobs:
  clean:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        variant: [ cached, cached/layer-cache, dual, for-cleaning, merged ]
    steps:
      - id: encode-name
        run: |
          PACKAGE_NAME="pull-request-${{ github.event.pull_request.number }}/${{ matrix.variant }}"
          # Poor man's urlencode
          ENCODED="${PACKAGE_NAME//\//%2F}"
          echo "package-name=${ENCODED}" >> "$GITHUB_OUTPUT"
      - run: >
          gh api
          --method DELETE 
          -H "Accept: application/vnd.github+json" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          /orgs/${{ github.repository_owner}}/packages/container/${{ steps.encode-name.outputs.package-name }}
        env:
          GH_TOKEN: ${{ secrets.GH_PACKAGE_CLEANUP_TOKEN }}
