on:
  push:
    branches: [ main ]
  pull_request: { }

jobs:
  check:
    uses: BlindfoldedSurgery/actions-actions/.github/workflows/commitizen-check.yml@v2

  bump:
    uses: BlindfoldedSurgery/actions-actions/.github/workflows/commitizen-bump.yml@v2
    with:
      publish-major-tag: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_PR_TOKEN }}
